### ISSUE TITLE
Editor - Custom Types

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#198]
How do we define custom types?

## Decision
Currently, we're thinking about defining all custom types in pure markdown as well.

This was the first draft:
```markdown
#custom
type: audio
id: 123456789
action: start, loop
volume: 0.1
comment: This is a comment
```

### Backend

- [ ] Think about where to Serialize/Deserialize: Frontend or Backend?
- [ ] Define a markdown structure for custom Scriptcells such as the Audio Scriptcell

**Comment by vin-ni** [comment]
@capital-G Can we close this?

**Comment by capital-G** [comment]
Yes :)
