### ISSUE TITLE
Artificial Voice Quality

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#382]
How to get better quality of the TTS?
- use more expensive model
- use ssml
- ...

Let's discuss :)

**Comment by capital-G** [comment]
Add new voices seen in https://cloud.google.com/text-to-speech

* `neural2`
* `polyglot`

New default should be: female (new default) `de-DE-Neural2-C` and male default `de-DE-Neural2-B`

Remove basic, and also add cache checking for voice as well.
