### ISSUE TITLE
Drag and drop does not work

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#388]
Rearanging the script cells via drag and drop and saving them reverts to the old order.

**Comment by capital-G** [comment]
@vin-ni :D

https://github.com/Gencaster/gencaster/assets/8267062/0b55cc88-1d7e-4fc5-ad93-1a24e186f9a3

**Comment by vin-ni** [comment]
Yes, this bug is referenced to fix here: 
https://github.com/Gencaster/gencaster/issues/463#issue-1749579854
