### ISSUE TITLE
Pre-Commit does not check for blank lines at EOF

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#437]
EOF should be always a blank line

              normally the CI should fail as pre-commit forces a blank line at the ending of a file.
Will take a look at this in a new issue.

_Originally posted by @capital-G in https://github.com/Gencaster/gencaster/pull/436#discussion_r1210859611_

**Comment by capital-G** [comment]
It seems that pre-commit is not performing any linting checks on the editor at all right now - needs investigation.

**Comment by vin-ni** [comment]
I usually run this: `pre-commit run --all-files`

But something is off. I don't think this would be correct with no spaces at all. But thats what the linter wanted o.O
<img width="589" alt="Screenshot 2023-06-09 at 14 33 42" src="https://github.com/Gencaster/gencaster/assets/9806572/172d4ffb-877b-4291-9865-ab83a2442689">

**Comment by capital-G** [comment]
Closed since I have not experienced any errors with it anymore since a while. Reopen if necessary.
