### ISSUE TITLE
Lock repositioning start node and prevent deleting

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#458]
- [ ] On start pan to starting node
- [ ] prevent deleting

**Comment by capital-G** [comment]
I don't think a fixation of the start node at (0,0) is necessary - from my experience with visuals programing languages it is always good to have everything relative and nothing absolute (most languages don't even restrict the canvas for this reason) - this allows the user to construct a clean graph based on the situation and not froce the user to build around (0,0)

**Comment by vin-ni** [comment]
I totally agree in general. The problem is:

1. V network graph only offers a `fitToContents` method, which manipulates zoom and panning to fit everything into the viewport.
2. But while running this, it completely messes with the internal numbers of `v-network-graphs` bugging the frontend animations. (for examle if you have just one node, it zooms super far into the graph and the nodes coordinates end upt beeing [0.00000015, 0.0000000047]. Therefore I disabled `zoom` and `fitToContents` to just start at 0,0 in the viewport.
3. This could create the problem, that if a user moves the starting point to [999,999] for any reason, future users will not find the graph.

Therefore I think there are thre options:

1.  Fix the first node to [0,0]
2. re-enable `fitToContents`
3. Accept that users might get lost / lose their graph

**Comment by capital-G** [comment]
Wouldn't be the easiest solution to simply look up the position of the start node and set this as a view point of the graph when one enters it?

> 2\. But while running this, it completely messes with the internal numbers of `v-network-graphs` bugging the frontend animations. (for examle if you have just one node, it zooms super far into the graph and the nodes coordinates end up beeing [0.00000015, 0.0000000047]. Therefore I disabled `zoom` and `fitToContents` to just start at 0,0 in the viewport.

I think this should be feasible by setting the `maxZoomLevel` as described in https://dash14.github.io/v-network-graph/reference/configurations.html ?

**Comment by vin-ni** [comment]
That's the 4th option :)
