### ISSUE TITLE
SyncPlay should be default for Audio

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#459]
Can we add `SyncPlay` as default for the editor? 
Per Node editor one sets usually only one background music and multiple Sync audio files.

What do you think @capital-G ?

**Comment by capital-G** [comment]
Sounds fine.

The backend already uses this as a default

https://github.com/Gencaster/gencaster/blob/bb0ec4c5d7ed3d4fafaaad970503e9c67dd5767c/caster-back/story_graph/models.py#L281-L284

So maybe add it as a default in the editor?

https://github.com/Gencaster/gencaster/blob/bb0ec4c5d7ed3d4fafaaad970503e9c67dd5767c/caster-editor/src/components/ScriptCellAudio.vue#L34-L39
