### ISSUE TITLE
Audio file list UI bugs

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#463]
<img width="1791" alt="image" src="https://github.com/Gencaster/gencaster/assets/8267062/9c4a904c-ed1c-487d-ad8e-4249beafd280">

* [x] list too long / missing scroll
* [x] separators do not align
* [x] script cell text is not "blured" (z-index issue?)
* [x] not whole background is "blured"
* [x] I think I experienced some drag and drop issues once, especially mixing the audio file drag&drop with the drag & drop of the script cell order, but could not replicate it now
* [x] Cancel button is aligned/positioned

**Comment by vin-ni** [comment]
#460 Completed
