### ISSUE TITLE
New graphs have wrong assignment default

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster#501]
Something is broken here, most likely in strawberry? Not a high priority as it can be adjusted in the backend admin.

A simple fix would be to be more explicit here, but I think that it is worth to understand what goes wrong here.

https://github.com/Gencaster/gencaster/blob/30898d5fc5f2b7d34580b167611929da8e68d7be/caster-back/story_graph/models.py#L65-L70

https://github.com/Gencaster/gencaster/blob/30898d5fc5f2b7d34580b167611929da8e68d7be/caster-back/gencaster/schema.py#L465-L475

https://github.com/Gencaster/gencaster/blob/30898d5fc5f2b7d34580b167611929da8e68d7be/caster-editor/src/graphql.ts#L50-L69

where

https://github.com/Gencaster/gencaster/blob/30898d5fc5f2b7d34580b167611929da8e68d7be/caster-back/story_graph/types.py#L142-L152

and

https://github.com/Gencaster/gencaster/blob/30898d5fc5f2b7d34580b167611929da8e68d7be/caster-back/story_graph/types.py#L22

An example request looks like

```json
{
    "query": "mutation CreateGraph($graphInput: AddGraphInput!) {\n  addGraph(graphInput: $graphInput) {\n    name\n    uuid\n    nodes {\n      name\n      uuid\n      isEntryNode\n      __typename\n    }\n    __typename\n  }\n}",
    "operationName": "CreateGraph",
    "variables": {
        "graphInput": {
            "name": "CreateGraphTest",
            "displayName": "CreateGraphTest",
            "slugName": "creategraphtest",
            "publicVisible": true
        }
    }
}
```

**Comment by vin-ni** [comment]
@capital-G Is this still going wrong?

**Comment by capital-G** [comment]
Yes, somehow this is still a thing :/

**Comment by capital-G** [comment]
Closed via https://github.com/Gencaster/gencaster/pull/572
