### ISSUE TITLE
Default Template doesn't switch to end screen on end

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#530]
Currently, the end screen is not shown once the graph ends. Not sure if it's missing a listener in the template, or the graph is not sending an `end` signal.

![IMG_8FE951D6C0FE-1](https://github.com/Gencaster/gencaster/assets/9806572/64093be4-a3fb-43fe-996f-90996369405f)

**Comment by capital-G** [comment]
Must be something around here

https://github.com/Gencaster/gencaster/blob/326527db7870230dbd0c026159c3cb177a24cd61/caster-front/src/components/GraphPlayer.vue#L111-L133

and

https://github.com/Gencaster/gencaster/blob/326527db7870230dbd0c026159c3cb177a24cd61/caster-front/src/components/GraphPlayer.vue#L412-L420

If the backend can not consume any more nodes (aka rand into a dead end) it will tear down the ws connection aka subscription - I think currently the frontend code does not check for "has it been teared down? if so => end screen"

**Comment by capital-G** [comment]
Closed via https://github.com/Gencaster/gencaster/pull/571
