### ISSUE TITLE
Infinite Super Collider Bug

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#535]
If a super collider scriptcell is played, that isn't ab ndef, it theoritcally will keep playing forever on a channel.

Example:
```
  var snare, bdrum, hihat;
  var tempo = 4;

  tempo = Impulse.ar(tempo); // for a drunk drummer replace Impulse with Dust !!!
  snare = WhiteNoise.ar(Decay2.ar(PulseDivider.ar(tempo, 4, 2), 0.005, 0.5));
  bdrum = SinOsc.ar(Line.ar(120,60, 1), 0, Decay2.ar(PulseDivider.ar(tempo, 4, 0), 0.005, 0.5));
  hihat = HPF.ar(WhiteNoise.ar(1), 10000) * Decay2.ar(tempo, 0.005, 0.5);

  Out.ar(0, (snare + bdrum + hihat) * 0.1 ! 2)
}
```

This kept playing and overlapping on each channel used. 

Question:
How to handle this? Shoulds Super Collider reset when coming back to a channel? Or should we enforce the use of ndefs?
@capital-G

**Comment by capital-G** [comment]
Closed via https://github.com/Gencaster/gencaster/pull/576
