### ISSUE TITLE
Where to put Edge Logic?

### ISSUE THREAD

**Issue by vin-ni** [Gencaster/gencaster#97]
Situation: One node is pointing to 4 different other Nodes.

- [ ] Where is the logic that decides on what Edge to go?
- [ ] What does this logic look like?
- [ ] What happens if one deletes a node? Will the Edge

Not urgent for presentation. We'll be fine with linear connections.

**Comment by vin-ni** [comment]
Discussion result today:
- generally the end of a node decides on the next edge to walk. This ensures, we favor using existing edges -> edges get names / ids
- jumping to nodes directly is also possible but only via code.

**Comment by capital-G** [comment]
concept of aws connect

![phone-kolloquium](https://github.com/Gencaster/gencaster/assets/8267062/b3a8e682-ff8d-4a4b-a948-a6b2cb2695fd)

**Comment by capital-G** [comment]
* [ ] create `NEXT_NODE_UUID` stream variable

**Comment by capital-G** [comment]
Vueflow seems to allow for multiple exit within a node which would be a good fit?

https://vueflow.dev/examples/nodes/

**Comment by vin-ni** [comment]
Concept Sketch for the new Graph style with programmable output nodes.

- Starting node has no input node
- Script Editor enables to add custom output nodes

![new node sample](https://github.com/Gencaster/gencaster/assets/9806572/471462fb-f535-4f5e-be27-7fc5e9aec2a5)

**Comment by vin-ni** [comment]
Closed by https://github.com/Gencaster/gencaster/pull/553
